### ISSUE TITLE
require Sproutcore-datastore Fix

### ISSUE THREAD

**Issue by Wkasel** [LuisSala/demogram-basic#1]
Hey Luis,

Was playing with this, and saw an error "method create, undefined", or something to that tune. I figured it wasn't pulling in sproutcore-datastore, so i added spade.require('sproutcore-datastore'); to line 3. It's a little late in the evening for me to bother doing a pull request, plus it's such a simple fix. Just FYI.

Cheers,

William

**Comment by LuisSala** [comment]
Just pushed out the fixes. Thanks!
